name: CI

on: [push]

permissions:
  id-token: write
  contents: read

env:
  YQ_VERSION: "4.25.1"
  LAMBDA_ZIP_VERSION: "v1.2.0"
  LAMBDA_ZIP_BUCKET: "axiom-cloudformation-dev"
  LAMBDA_ZIP_KEY: "axiom-cloudwatch-forwarder/$LAMBDA_ZIP_VERSION/forwarder.zip"

jobs:
  terraform:
    name: "terraform fmt"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.4"
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -check
